export const selectors = {
  appLayout: '.app-layout',
  sidebar: 'aside.sidebar',
  mainContent: 'main.main-content',
  sidebarCollapse: 'aside.sidebar .collapse-btn',
  queueList: '.queue-list',
  queueEmpty: '.queue-empty',
  queueRound: '.queue-round',
  queueRoundExpanded: '.queue-round.is-expanded',
  queueRoundToggle: '.queue-round-toggle',
  queueRoundRemove: '.queue-round-remove',
  queueRoundPrompt: '.queue-round-prompt',
  queueClearAll: '.queue-summary-clear',
  queueItem: '.queue-item',
  queueItemText: '.queue-item-text',
  queueItemRemove: '.queue-item-remove',
  paneChip1: '.pane-toggle .chip:nth-child(1)',
  paneChip3: '.pane-toggle .chip:nth-child(3)',
  paneNewAllButton: '.new-all-btn',
} as const;
