import type { ProviderInject } from '../types'

export const inject: ProviderInject = {
  inputSelectors: [
    'rich-textarea .ql-editor',
    'rich-textarea .ql-editor p',
    "div.ql-editor[contenteditable='true']",
    'div.ql-editor p',
    'rich-textarea textarea',
    'textarea.ql-editor',
    "div[contenteditable='true'][aria-label*='Enter']",
    "textarea[aria-label*='Enter']",
    "textarea[aria-label*='Ask']",
    "textarea[aria-label*='Message']",
    "div[contenteditable='true'][role='textbox']",
    "div[contenteditable='true']",
    'textarea',
  ],
  submitSelectors: [
    "button[aria-label*='Send']",
    "button[mattooltip*='Send']",
    'button.send-button',
    "form button[type='submit']",
  ],
  responseSelectors: [
    'message-content div.markdown.markdown-main-panel',
    'div.markdown.markdown-main-panel',
    '.response-container-content .markdown',
    'model-response .markdown',
    '.model-response-text .markdown',
  ],
  streamingIndicatorSelectors: [
    "button[aria-label='Stop response']",
    "button[aria-label*='Stop']",
    "button[mattooltip*='Stop']",
    'button.send-button.stop',
    '.send-button-container .stop-icon',
    "mat-icon[fonticon='stop']",
    "mat-icon[data-mat-icon-name='stop']",
    "button:has(mat-icon[fonticon='stop'])",
    "model-response:last-of-type mat-icon[fonticon='stop']",
    "model-response:last-of-type [aria-busy='true']",
    'model-response:last-of-type .typing-indicator',
    "model-response:last-of-type mat-progress-bar[mode='indeterminate']",
  ],
  completeIndicatorSelectors: [
    'model-response:last-of-type message-actions button[aria-label*="Copy"]',
    'model-response:last-of-type button[aria-label="Double-check response"]',
    'model-response:last-of-type message-actions',
  ],
}
